To install any package, this config will be using ~use-package~. So
before proceeding ahead with anything, install ~use-package~. Check this [[https://ianyepan.github.io/posts/setting-up-use-package/][~use-package~ tutorial]].

#+BEGIN_SRC emacs-lisp
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
  (eval-and-compile
    (setq use-package-always-ensure t
	  use-package-expand-minimally t))
#+END_SRC

Setting ~use-package-always-ensure~ to ~t~ saves us the trouble of
having to specify ~:ensure t~ in any future packages we’d like to
declare and install. The ~:ensure~ macro basically makes sure that the
packages are correctly installed at every startup, and automatically
installs the missing ones for you.


* Theme

** Before Initializing any theme.
Initialize theme at start, so that any other visual changes won’t be
overridden by default theme changes.

Function to disable all applied themes.

#+BEGIN_SRC emacs-lisp
  (defun cc/disable-all-themes ()
    "Disable all active themes."
    (interactive)
    (dolist (i custom-enabled-themes)
      (disable-theme i)))
#+END_SRC

Add advice to ~load-theme~ to disable all themes before loading new theme.

#+BEGIN_SRC emacs-lisp
  (defadvice load-theme (before disable-themes-first activate)
    (cc/disable-all-themes))
#+END_SRC

** Initializing the theme

#+BEGIN_SRC emacs-lisp
  (use-package solarized-theme
    :config
    (load-theme 'solarized-dark t))
#+END_SRC

* Packages

Refresh contents of all packages in ~package-archives~ before starting.

#+BEGIN_SRC emacs-lisp
  (package-refresh-contents)
#+END_SRC

** Org

Check if ORG Mode is not installed and install it.

#+BEGIN_SRC emacs-lisp
  (unless (package-installed-p 'org)
    (package-refresh-contents)
    (package-install 'org))
#+END_SRC

** which-keys

   Display available key bindings in pop-up
#+BEGIN_SRC emacs-lisp
  ;; Install which keys
  (unless (package-installed-p 'which-key)
    (package-refresh-contents)
    (package-install 'which-key))

  ;; Enable which-keys
  (which-key-mode)
#+END_SRC

** Evil

#+BEGIN_SRC emacs-lisp
  (unless (package-installed-p 'evil)
    (package-install 'evil))

  (require 'evil)
  (evil-mode 1)
#+END_SRC


* Genral

** Appearance

Hide toolbar, menubar and scrollbar.

#+BEGIN_SRC emacs-lisp
(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
#+END_SRC

Display line numbers

#+BEGIN_SRC emacs-lisp
  (display-line-numbers-mode)
#+END_SRC

Make line numbers relative

#+BEGIN_SRC emacs-lisp
  (setq display-line-numbers 'relative)
#+END_SRC
